sudo: enabled
language: minimal

matrix:
  include:
  - env: ARGS="--resolver lts-9  --compiler ghc-8.0.2 --stack-yaml stack_lts-9.yaml"
  - env: ARGS="--resolver lts-11 --compiler ghc-8.2.2 --stack-yaml stack_lts-12.yaml"
  - env: ARGS="--resolver lts-12 --compiler ghc-8.4.4 --stack-yaml stack_lts-12.yaml"
  - env: ARGS="--resolver lts-13 --compiler ghc-8.6.4"
  - env: ARGS="--resolver lts-14 --compiler ghc-8.6.5"
  - env: ARGS="--resolver lts-15 --compiler ghc-8.8.2"
  - env: ARGS="--resolver lts-16 --compiler ghc-8.8.3"
  - env: ARGS="--resolver nightly"

  allow_failures:
  - env: ARGS="--resolver nightly"

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script: travis/run.sh

cache:
  directories:
  - $HOME/.stack
