name:                safe-json
version:             1.1.0
github:              "Vlix/safe-json"
license:             MIT
author:              "Felix Paulusma"
maintainer:          "felix.paulusma@gmail.com"
copyright:           "2019 Felix Paulusma"
# Metadata used when publishing your package
synopsis:            Automatic JSON format versioning
category:            "JSON"
tested-with:         GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.4, GHC == 8.6.4, GHC == 8.6.5, GHC == 8.8.3

extra-source-files:
- README
- ChangeLog.md
- test/json/*

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: >
    This library aims to make the updating of JSON formats or contents,
    while keeping backward compatibility, as painless as possible.
    The way this is achieved is through versioning and defined migration
    functions to migrate older (or newer) versions to the one used.


    The library mainly consists of two classes:


    * @SafeJSON a@: Defines the version of @a@ and if (and how) it is
    migratable.


    * @Migrate a@: Defines the data type (@MigrateFrom a@) that can be
    migrated to @a@ and how to migrate from that type.


    Using these two classes, JSON serialized data types will stay
    parsable, even after format changes.


    For a more in-depth explanation and examples,
    please see the README at <https://github.com/Vlix/safe-json#readme>


dependencies:
- aeson                 >= 1.4.1      && < 1.6
- base                  >= 4.9        && < 5
- bytestring            >= 0.10.8.1   && < 0.11
- containers            >= 0.5.7.1    && < 0.7
- dlist                 >= 0.8.0.3    && < 0.9
- hashable              >= 1.2.6.1    && < 1.4
- scientific            >= 0.3.5.2    && < 0.4
- tasty                 >= 0.11.3     && < 1.4
- tasty-hunit           >= 0.9.2      && < 0.11
- tasty-quickcheck      >= 0.8.4      && < 0.11
- text                  >= 1.2.3      && < 1.3
- time                  >= 1.6.0.1    && < 1.10
- unordered-containers  >= 0.2.9      && < 0.3
- uuid-types            >= 1.0.3      && < 1.1
- vector                >= 0.12.0.1   && < 0.13

library:
  source-dirs: src
  exposed-modules:
    - Data.Aeson.Safe
    - Data.SafeJSON
    - Data.SafeJSON.Test
  default-extensions:
    - OverloadedStrings

tests:
  safe-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - generic-arbitrary     >= 0.1.0    && < 0.2
      - safe-json             >= 1.0      && < 1.2
      - quickcheck-instances  >= 0.3.16   && < 0.4
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - temporary             >= 1.2.1.1  && < 1.4
      - uuid                  >= 1.3.13   && < 1.4
    default-extensions:
      - OverloadedStrings
