name:                safe-json
version:             0.1.0
github:              "Vlix/safe-json"
license:             MIT
author:              "Felix Paulusma"
maintainer:          "felix.paulusma@gmail.com"
copyright:           "2019 Felix Paulusma"
# Metadata used when publishing your package
synopsis:            Automatic JSON format versioning
category:            "JSON"

extra-source-files:
- README.md
- ChangeLog.md


# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see README at <https://github.com/Vlix/safe-json#readme>

dependencies:
- aeson                 >= 1.4.2    && < 1.5
- base                  >= 4.12     && < 5
- bytestring            >= 0.10.8.2 && < 0.11
- containers            >= 0.6.0.1  && < 0.7
- dlist                 >= 0.8.0.5  && < 0.9
- hashable              >= 1.2.7    && < 1.3
- scientific            >= 0.3.6.2  && < 0.4
- tasty                 >= 1.2      && < 1.3
- tasty-hunit           >= 0.10.0.1 && < 0.11
- tasty-quickcheck      >= 0.10     && < 0.11
- text                  >= 1.2.3.1  && < 1.3
- time                  >= 1.8.0.2  && < 1.9
- unordered-containers  >= 0.2.9    && < 0.3
- uuid-types            >= 1.0.3    && < 1.1
- vector                >= 0.12.0.2 && < 0.13

library:
  source-dirs: src
  exposed-modules:
    - Data.Aeson.Safe
    - Data.SafeJSON
    - Data.SafeJSON.Test
  default-extensions:
    - OverloadedStrings

tests:
  safe-json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - generic-arbitrary
      - safe-json
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - temporary
      - uuid
    default-extensions:
      - OverloadedStrings
